name: Deploy to production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: actions/setup-ruby@v1
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Build website
        run: bundle exec jekyll build -b "/ulx_docs"
      - name: Install Node.js
        uses: actions/setup-node@v1
      - name: Install html-minifier
        run: npm install html-minifier -g
      - name: Minify HTML
        run: |
          npx html-minifier \
            --collapse-boolean-attributes \
            --collapse-whitespace \
            --decode-entities \
            --minify-css \
            --minify-js \
            --process-conditional-comments \
            --remove-attribute-quotes \
            --remove-comments \
            --remove-empty-attributes \
            --remove-optional-tags \
            --remove-redundant-attributes \
            --remove-script-type-attributes \
            --remove-style-link-type-attributes \
            --sort-attributes \
            --sort-class-name \
            --trim-custom-fragments \
            --use-short-doctype \
            --input-dir _site \
            --output-dir _site \
            --file-ext html
      - name: Install clean-css-cli
        run: npm install clean-css-cli -g
      - name: Minify CSS
        run: |
          shopt -s globstar nullglob
          npx cleancss \
            --level 2 \
            --output _site/css/**/*.css \
            _site/css/main.css
      - name: Install brotli
        run: sudo apt-get install brotli
      - name: Compress assets
        run: find _site -type f \( -iname \*.html -o -iname \*.css -o -iname \*.js \) -print0 | xargs -0 brotli --
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Publish website
        run: echo 'put -r _site/.' | sshpass -p ${{ secrets.SFTP_PASSWORD }} sftp -oStrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@ulyssesmod.net:ulyssesmod.net/ulx_docs
